services:
  api:
    build:
      target: dev
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
    develop:
      watch:
        - path: ./api/src
          action: sync
          target: /app/src
        - path: ./package.json
          action: rebuild

  web:
    build:
      target: dev
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`)"
    develop:
      watch:
        - path: ./web/src
          action: sync
          target: /app/src
        - path: ./web/public
          action: sync
          target: /app/public
        - path: ./package.json
          action: rebuild

  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web-traffic

networks:
  web-traffic:
    driver: bridge
    name: web-traffic
