services:
  api:
    image: marvinalegre/pokemath-api:latest
    restart: always
    labels:
      - "traefik.http.routers.api.rule=Host(`pokemath.testingg.bid`) && PathPrefix(`/api`)"
      - "traefik.http.routers.whiteboard.entrypoints=websecure"
      - "traefik.http.routers.whiteboard.tls.certresolver=myresolver"

  web:
    image: marvinalegre/pokemath-web:latest
    environment:
      - NEXT_PUBLIC_API_URL=https://pokemath.testingg.bid/api
    restart: always
    labels:
      - "traefik.http.routers.frontend.rule=Host(`pokemath.testingg.bid`)"
      - "traefik.http.routers.whiteboard.entrypoints=websecure"
      - "traefik.http.routers.whiteboard.tls.certresolver=myresolver"

networks:
  web-traffic:
    external: true
