services:
  api:
    build:
      target: final
    environment:
      - NODE_ENV=production
    restart: always
    labels:
      - "traefik.http.routers.api.rule=Host(`pokemath.testingg.bid`) && PathPrefix(`/api`)"
      - "traefik.http.routers.whiteboard.entrypoints=websecure"
      - "traefik.http.routers.whiteboard.tls.certresolver=myresolver"

  web:
    build:
      target: final
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://pokemath.testingg.bid/api
    restart: always
    labels:
      - "traefik.http.routers.frontend.rule=Host(`pokemath.testingg.bid`)"
      - "traefik.http.routers.whiteboard.entrypoints=websecure"
      - "traefik.http.routers.whiteboard.tls.certresolver=myresolver"

networks:
  web-traffic:
    driver: bridge
    name: web-traffic
