name = "pokemath3"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-12-11"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "foobar"
database_id = "6146e4c1-8a08-4eb9-b9d0-33ba3c629482"