name = "pokemath"
main = "src/index.js"
compatibility_date = "2024-12-11"
compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pokemath"
database_id = "d11ea8d1-f646-4f97-95ae-f8c21244bc41"
